apiVersion: apps/v1
kind: Deployment
metadata:
  name: nav-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nav-app
  template:
    metadata:
      labels:
        app: nav-app
    spec:
      containers:
      - name: nav-app
        image: poridhi/nav-app:v1.7.6
        ports:
        - containerPort: 80
          name: http