apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-service
spec:
  ingressClassName: nginx
  rules:
  - host: matrix.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tech-blog
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-service
spec:
  ingressClassName: nginx
  rules:
  - host: glitch.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio
            port:
              number: 80