apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-frontend
  template:
    metadata:
      labels:
        app: store-frontend
    spec:
      containers:
      - name: store-frontend
        image: poridhi/store-app:v2.4
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "https://ryuzaki.me/fastapi"